export const PRICING = {
  amount: 75,
  currency: '€',
  period: 'mois',
  label: '75€/mois',
  planName: 'ResellQ Pro',
} as const

export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 29,
    currency: '€',
    period: 'mois',
    description: 'Pour commencer avec un accès simple et efficace.',
    badge: 'Essentiel',
    highlight: false,
    cta: 'Commencer',
    tokenLabel: '250 crédits IA / mois',
    features: [
      '5 catégories incluses',
      'Top 20 deals',
      'Alertes 5/jour',
      'Watchlist 20 articles',
      'Assistant IA & recherche produit (consomme des crédits selon les mots/requêtes)',
      'Deal Finder basique',
    ],
    missingFeatures: [
      'Historique des prix',
      'Exports',
      'Rapports',
      'Notifications instantanées',
      'Support prioritaire',
      'Et plus encore...',
    ],
    businessExtras: [],
    limitations: ['Pas d\'historique des prix', 'Pas d\'exports', 'Deal Finder basique'],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 75,
    currency: '€',
    period: 'mois',
    description: 'Le bon équilibre entre outils et performance.',
    badge: 'Le plus choisi',
    highlight: true,
    cta: 'Passer au Pro',
    tokenLabel: '2 000 crédits IA / mois',
    features: [
      '20 catégories incluses',
      'Top 100 deals',
      'Historique des prix 90 jours',
      'Alertes illimitées',
      'Watchlist 250 articles',
      'Assistant IA prioritaire & recherche produit',
      'Exports CSV / Excel',
      'Deal Finder avancé',
      'Rapports simples',
      'Notifications instantanées',
      'Support prioritaire',
    ],
    missingFeatures: [
      'Toutes les catégories',
      'Deals illimités',
      'Historique des prix illimité',
      'Exports PDF + API',
      'Deal Finder IA prioritaire',
      'Rapports avancés',
      'Support VIP',
    ],
    businessExtras: [],
    limitations: ['Pas de PDF / API', 'Pas de dashboard Business', 'IA coach non inclus'],
  },
  {
    id: 'business',
    name: 'Business',
    price: 149,
    currency: '€',
    period: 'mois',
    description: 'Pour les revendeurs sérieux qui veulent dominer le marché.',
    badge: 'Business',
    highlight: false,
    cta: 'Devenir Business',
    tokenLabel: 'IA illimitée',
    features: [
      'Toutes les catégories incluses',
      'Top deals illimité',
      'Historique des prix illimité',
      'Alertes temps réel',
      'Watchlist illimitée',
      'Exports CSV / Excel / PDF',
      'Assistant IA prioritaire & recherche produit illimités',
      'Deal Finder IA prioritaire',
      'Rapports avancés',
      'Notifications instantanées prioritaires',
      'Support priorité + Discord privé',
    ],
    missingFeatures: [],
    limitations: [],
    businessExtras: [
      'Détection 2 à 5 min avant les autres',
      'Score de rentabilité IA détaillé',
      'Historique complet : demande, saisonnalité, meilleur/pire mois',
      'Heatmap Vinted des catégories en explosion',
      'IA Coach intelligent',
      'Scanner de marques',
      'Scanner de vendeurs',
      'Dashboard Business : ROI, bénéfices, temps moyen de vente',
    ],
  },
] as const

export const PLAN_FEATURES = [
  'Tableau de bord analytique premium',
  'Top ventes sur toutes les catégories',
  'Recherche produit illimitée',
  'Agent IA illimité',
  'Deal Finder et opportunités',
  'Insights et prédictions de marché',
  'Export CSV / Excel / PDF',
  'Listes de suivi et alertes',
  'Support prioritaire',
] as const
